version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      # - run: CI=true npm run build

  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "testing stuff"
      - run: npm install
      # - run: npm test

  test_2:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "testing final"

workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - test_2
      - test:
          requires:
            - test_2
